import './globals.css';
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

const inter = Montserrat({ subsets: ['cyrillic-ext'] })

export const metadata: Metadata = {
  title: 'Hotel Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="wrapper">
        <Header />
        <main className="content container">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
